# Generated by Django 5.0.7 on 2024-07-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_telegram2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telegram2',
        ),
    ]
