# Generated by Django 5.0.7 on 2024-07-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контактная информация',
            },
        ),
    ]
