# Generated by Django 5.0.7 on 2024-07-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_count', models.IntegerField(verbose_name='Количество  проведенных уроков')),
                ('student_count', models.IntegerField(verbose_name='Количество студентов')),
                ('course', models.IntegerField(verbose_name='Количество курсов')),
                ('awards', models.IntegerField(verbose_name='Количество наград')),
            ],
        ),
    ]
