# Generated by Django 5.0.7 on 2024-07-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Информация о нашем учебном центре', 'verbose_name_plural': 'Информация о нашем учебном центре'},
        ),
    ]
