# Generated by Django 5.0.7 on 2024-07-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_information_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='photo3',
        ),
    ]
