# Generated by Django 5.0.7 on 2024-07-27 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_remove_settings_photo1_remove_settings_photo2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Smtp',
        ),
    ]
