# Generated by Django 5.0.7 on 2024-08-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_delete_smtp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('email', models.CharField(max_length=155, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявка на Telegram2',
                'verbose_name_plural': 'Заявки на Telegram2',
            },
        ),
    ]
