# Generated by Django 5.0.7 on 2024-07-27 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegram2',
            old_name='name',
            new_name='fullname',
        ),
    ]
