# Generated by Django 5.0.7 on 2024-07-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_rename_name_telegram2_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram2',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
    ]
