# Generated by Django 5.0.7 on 2024-07-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_telegram2_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegram2',
            old_name='message',
            new_name='textarea',
        ),
    ]
