# Generated by Django 5.0.7 on 2024-07-27 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_rename_message_telegram2_textarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegram2',
            old_name='textarea',
            new_name='message',
        ),
    ]
